image: Ubuntu

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - whoami
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose --version
  - sh startMysqlEnv.sh
  - chmod +x ./gradlew

build_script:
  - ps: ./gradlew test --info "-Dselenide.headless=true"

